// Owl - www.owlclient.com
// Copyright (c) 2012-2018, Adalid Claure <aclaure@gmail.com>
#include <QCryptographicHash>

#include <boost/test/unit_test.hpp>
#include <boost/test/data/test_case.hpp>

#include <iostream>

#include <spdlog/spdlog.h>
#include <spdlog/sinks/stdout_color_sinks.h>

#include "../src/Utils/WebClient.h"

namespace data = boost::unit_test::data;

BOOST_AUTO_TEST_SUITE(WebClientTests)

std::tuple<const char*, const char*, long> statusData[]
{
    std::tuple<const char*, const char*, long>
    {
        "https://httpstat.us/200",
        "200 OK",
        200
    },
    std::tuple<const char*, const char*, long>
    {
        "https://httpstat.us/201",
        "201 Created",
        201
    },
    std::tuple<const char*, const char*, long>
    {
        "https://httpstat.us/202",
        "202 Accepted",
        202
    },
    std::tuple<const char*, const char*, long>
    {
        "https://httpstat.us/404",
        "404 Not Found",
        404
    },
    std::tuple<const char*, const char*, long>
    {
        "https://httpstat.us/429",
        "429 Too Many Requests",
        429
    },
    std::tuple<const char*, const char*, long>
    {
        "https://httpstat.us/502",
        "502 Bad Gateway",
        502
    }
};

BOOST_DATA_TEST_CASE(statusTests, data::make(statusData), url, expectedResponse, expectedStatus)
{
    if (!spdlog::get("Owl"))
    {
        spdlog::stdout_color_mt("Owl")->set_level(spdlog::level::off);
    }

    owl::WebClient client;
    client.setThrowOnFail(false);
    auto reply = client.GetUrl(QString::fromLatin1(url), owl::WebClient::NOTIDY | owl::WebClient::NOCACHE);
    BOOST_REQUIRE(reply != nullptr);
    BOOST_CHECK_EQUAL(reply->data().toStdString(), expectedResponse);
    BOOST_CHECK_EQUAL(reply->status(), expectedStatus);
}

// [0] - the initial url
// [1] - the expected finalUrl
std::tuple<const char*, const char*> redirectData[]
{
    std::tuple<const char*, const char*>
    {
        "http://google.com",
        "http://www.google.com/"
    },
    std::tuple<const char*, const char*>
    {
        "http://amb.la",
        "https://amb.la/"
    },
    std::tuple<const char*, const char*>
    {
        "http://lulzapps.com",
        "http://www.owlclient.com/"
    }
};

BOOST_DATA_TEST_CASE(redirectTest, data::make(redirectData), url, expectedFinalUrl)
{
    if (!spdlog::get("Owl"))
    {
        spdlog::stdout_color_mt("Owl")->set_level(spdlog::level::off);
    }

    owl::WebClient client;
    client.setThrowOnFail(false);
    owl::WebClient::ReplyPtr reply = client.GetUrl(QString::fromLatin1(url), owl::WebClient::NOTIDY | owl::WebClient::NOCACHE);
    BOOST_CHECK_EQUAL(reply->finalUrl(), expectedFinalUrl);
}

// The SHA1 hashes are generated by viewing the source at
// https://codebeautify.org/source-code-viewer and then
// copying/pasting the text into the tool located at
// http://onlinemd5.com/. This selection of webpages were
// choosen because of the likelyhood that they will 
// never change.
std::tuple<const char*, const char*> webtextData[]
{
    std::tuple<const char*, const char*>
    {
        "http://www.cnn.com/US/OJ/",
        "67252B9BD74AB1080A508609496B88028C4403A6"
    },
    std::tuple<const char*, const char*>
    {
        "http://itcorp.com/",
        "A85DBDF7019E51724A29D8BAF1BE03B6710C1F7C"
    },
    std::tuple<const char*, const char*>
    {
        "https://www.york.ac.uk/teaching/cws/wws/webpage1.html",
        "A3E86B5B146DCA332F862A8096158E009BEBAB23"
    },
    std::tuple<const char*, const char*>
    {
        "http://web.ics.purdue.edu/~gchopra/class/public/pages/webdesign/05_simple.html",
        "9F871718676BD6175EDE3EECAD1A9D137E81E842"
    },
//   std::tuple<const char*, const char*>
//   {
//      "http://www.columbia.edu/~fdc/sample.html",
//      "AC23DF162A142F7657C0573923A51D7D611D0396"
//  }    
};

BOOST_DATA_TEST_CASE(webtextTest, data::make(webtextData), url, expectedhash)
{
    if (!spdlog::get("Owl"))
    {
        spdlog::stdout_color_mt("Owl")->set_level(spdlog::level::off);
    }

    owl::WebClient client;
    client.setThrowOnFail(false);

    QString rawtext = client.DownloadString(QString::fromStdString(url), owl::WebClient::NOTIDY);
    QByteArray hash = QCryptographicHash::hash(rawtext.toUtf8(), QCryptographicHash::Sha1);
    const QString result = QString{ hash.toHex() }.toUpper();

    BOOST_CHECK_EQUAL(result.toStdString(), expectedhash);
}


BOOST_AUTO_TEST_SUITE_END()
